CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Notes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedOn" timestamp with time zone NOT NULL,
    "Content" text NULL,
    CONSTRAINT "PK_Notes" PRIMARY KEY ("Id")
);

INSERT INTO "Notes" ("Id", "Content", "CreatedOn", "UpdatedOn")
VALUES (1, 'Finish Youtube video', TIMESTAMPTZ '2023-01-30 13:46:01.173491Z', TIMESTAMPTZ '2023-01-30 13:46:01.173491Z');
INSERT INTO "Notes" ("Id", "Content", "CreatedOn", "UpdatedOn")
VALUES (2, 'Go to gym', TIMESTAMPTZ '2023-01-30 13:46:01.173491Z', TIMESTAMPTZ '2023-01-30 13:46:01.173491Z');
INSERT INTO "Notes" ("Id", "Content", "CreatedOn", "UpdatedOn")
VALUES (3, 'Go to grocery', TIMESTAMPTZ '2023-01-30 13:46:01.173491Z', TIMESTAMPTZ '2023-01-30 13:46:01.173491Z');

SELECT setval(
    pg_get_serial_sequence('"Notes"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Notes") + 1,
        nextval(pg_get_serial_sequence('"Notes"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230130134601_Init-table', '7.0.2');

COMMIT;

