// <auto-generated />
using System;
using BeanstalkNet.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BeanstalkNet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230130134601_Init-table")]
    partial class Inittable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BeanstalkNet.DataAccess.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Finish Youtube video",
                            CreatedOn = new DateTime(2023, 1, 30, 13, 46, 1, 173, DateTimeKind.Utc).AddTicks(4919),
                            UpdatedOn = new DateTime(2023, 1, 30, 13, 46, 1, 173, DateTimeKind.Utc).AddTicks(4919)
                        },
                        new
                        {
                            Id = 2,
                            Content = "Go to gym",
                            CreatedOn = new DateTime(2023, 1, 30, 13, 46, 1, 173, DateTimeKind.Utc).AddTicks(4919),
                            UpdatedOn = new DateTime(2023, 1, 30, 13, 46, 1, 173, DateTimeKind.Utc).AddTicks(4919)
                        },
                        new
                        {
                            Id = 3,
                            Content = "Go to grocery",
                            CreatedOn = new DateTime(2023, 1, 30, 13, 46, 1, 173, DateTimeKind.Utc).AddTicks(4919),
                            UpdatedOn = new DateTime(2023, 1, 30, 13, 46, 1, 173, DateTimeKind.Utc).AddTicks(4919)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
